### ISSUE TITLE
Erro na documentação

### ISSUE THREAD

**Issue by caf-3** [renatodev17/pdf-creator#3]
author:caf-3
Texto original **Se caso existir, ele retornará o valor undefined, caso contrário ele retornará o texto do cabeçalho principal da página**
Não deveria ser : 
**Caso exista retornará o texto do cabeçalho original da página, caso contrário ele retornará undefined**
?

**Comment by renatodev17** [comment]
Muito obrigado por me reportar isso. Farei a mudança
